mytimer=tmr.create()
mytimer:register(2000,1,function()
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.HIGH)
tmr.delay(1011000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.LOW)
tmr.delay(5000000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.HIGH)
tmr.delay(2000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.LOW)
tmr.delay(200)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.HIGH)
tmr.delay(1000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.LOW)
tmr.delay(5000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.HIGH)
tmr.delay(2000)
pinLED2=0
gpio.mode(pinLED2,gpio.OUTPUT)
gpio.write(pinLED2,gpio.LOW)
tmr.delay(200)
print("Uptime (probably):", tmr.time())

end)
mytimer:start()
